student_project/teachers/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, TextAreaField
from wtforms.validators import DataRequired, Email
from flask_wtf.file import FileAllowed, FileField


class TeacherForm(FlaskForm):
    teacher_name = StringField('Teacher name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    description = TextAreaField('Teacher description', validators=[DataRequired()])
    profile = FileField('Profile Picture', validators=[DataRequired(), FileAllowed(['png', 'jpg'])])
    submit = SubmitField('Add Teacher')

student_project/core/views.py
# core views file
from flask import Blueprint, render_template
from student_project.models import User
core_blueprint = Blueprint('core', __name__)

# More to come


@core_blueprint.route("/")
def index():
    students = User.query.all()
    print(students)
    return render_template("index.html", students=students)


@core_blueprint.route("/info")
def info():
    return render_template("info.html")

student_project/courses/views.py
from flask import Blueprint, render_template, redirect, url_for
from student_project.courses.forms import CourseForm
from student_project.models import Course
from flask_login import current_user, login_required
from student_project import db
from student_project.users.picture_handler import add_profile_pic

course_blueprint = Blueprint('courses', __name__)


@course_blueprint.route('/view-course')
def view_course():
    courses = Course.query.all()
    for course in courses:
        print(course.course_name)
    return render_template("course.html", courses=courses)


@course_blueprint.route("/add-course", methods=['GET', 'POST'])
@login_required
def add_course():
    form = CourseForm()
    if form.validate_on_submit():
        new_course = Course(course_name=form.course_name.data,
                            description=form.description.data,
                            user_id=current_user.id, teacher_id=current_user.id)
        db.session.add(new_course)
        db.session.commit()
        return redirect(url_for('courses.view_course'))
    return render_template('add_course.html', form=form)

student_project/teachers/views.py
from flask import Blueprint, render_template, redirect, url_for
from student_project.models import Teacher
from student_project.teachers.forms import TeacherForm
from student_project.users.picture_handler import add_profile_pic
from flask_login import current_user, login_required
from student_project import db
teacher_blueprint = Blueprint('teachers', __name__)


@teacher_blueprint.route("/view-teacher")
@login_required
def view_teacher():
    teachers = Teacher.query.all()
    return render_template("teacher.html", teachers=teachers)


@teacher_blueprint.route("/add-teacher", methods=['GET', 'POST'])
@login_required
def add_teacher():
    form = TeacherForm()
    if form.validate_on_submit():
        if form.profile.data:
            pic = add_profile_pic(form.profile.data)

        new_teacher = Teacher(teacher_name=form.teacher_name.data, email=form.email.data,
                              description=form.description.data, teach_profile=pic,
                              user_id=current_user.id)
        db.session.add(new_teacher)
        db.session.commit()
        return redirect(url_for('teachers.view_teacher'))
    return render_template("add_teacher.html", form=form)

student_project/users/views.py
# user/ views

from flask import Blueprint, render_template, flash, redirect, url_for, request
from student_project import db
from student_project.models import User
from student_project.users.forms import LoginForm, RegisterForm, AccountForm
from flask_login import login_required, login_user, logout_user, current_user
from student_project.users.picture_handler import add_profile_pic, admin_only

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash("Logged out successfully😍")
    return redirect(url_for('core.index'))


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(full_name=form.full_name.data, email=form.email.data, phone_number=form.phone_number.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("You have registered successfully, Now you can log In.🥰")
        return redirect(url_for('users.login'))
    return render_template("register.html", form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == "POST":
        user = User.query.filter_by(email=request.form.get("email")).first()
        if user.check_password(request.form.get("password")) and user is not None:
            login_user(user)
            flash("Logged In successfully😍")
            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('core.index')
            return redirect(next)
        print(request.form.get("email"))
        print("hello")
    return render_template("login.html", form=form)


@user_blueprint.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = AccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            pic = add_profile_pic(form.picture.data)
            current_user.profile_pic = pic
        current_user.full_name = form.full_name.data
        current_user.email = form.email.data
        current_user.phone_number = form.phone_number.data
        db.session.commit()
        flash("Your account has been updated!😇")
    elif request.method == 'GET':
        form.full_name.data = current_user.full_name
        form.email.data = current_user.email
        form.phone_number.data = current_user.phone_number
    profile_image = url_for('static', filename='images/' + current_user.profile_pic)
    return render_template("account.html", form=form, profile_image=profile_image, full_name=current_user.full_name)


@user_blueprint.route("/admin-page")
@admin_only
def admin_page():
    return render_template("admin.html")

@user_blueprint.route("/student-course")
def student_course():

    pass

student_project/templates/account.html
{% extends "base.html" %}

{% block content %}
<div class="content-section">
    <div align="center">
        <h1 style="color: white;">Welcome to the account for  {{ full_name }}</h1>
        <img align="center" class="rounded-circle" src="{{ profile_image }}">
    </div>
</div>

<div class="container">
    <div class="jumbotron">
        <form method="POST" action="", enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.full_name.label() }}
                {{ form.full_name(class='form-control') }}
            </div>   <br>
            <div class="form-group">
                {{ form.email.label() }}
                {{ form.email(class='form-control') }}
            </div>  <br>
            <div class="form-group">
                {{ form.phone_number.label() }}
                {{ form.phone_number(class='form-control') }} <br>
            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class='form-control') }} <br>
            </div>
            {{ form.submit(class='btn btn-primary') }}

        </form>
    </div>
</div>


{% endblock %}

student_project/templates/add_course.html
{% extends "base.html" %}
{% block content %}

  <div class="container">
      <div class="jumbotron">
          <form method="POST" action="", enctype="multipart/form-data">
              {{ form.hidden_tag() }}
              <div class="form-group">
                  {{ form.course_name.label() }}
                  {{ form.course_name() }}
              </div>

               <div class="form-group">
                  {{ form.description.label() }}
                  {{ form.description() }}
              </div>
              <div class="form-group">
                  {{ form.submit(class='btn btn-outline-primary') }}
              </div>

          </form>
      </div>

  </div>


{% endblock %}

student_project/templates/add_teacher.html
{% extends "base.html" %}
{% block content %}

  <div class="container">
      <div class="jumbotron">
          <form method="POST" action="", enctype="multipart/form-data">
              {{ form.hidden_tag() }}
              <div class="form-group">
                  {{ form.teacher_name.label() }}
                  {{ form.teacher_name() }}
              </div>

              <div class="form-group">
                  {{ form.email.label() }}
                  {{ form.email() }}
              </div>

               <div class="form-group">
                  {{ form.description.label() }}
                  {{ form.description() }}
              </div>

               <div class="form-group">
                  {{ form.profile.label() }}
                  {{ form.profile() }}
              </div>
              <div class="form-group">
                  {{ form.submit(class='btn btn-outline-primary') }}
              </div>

          </form>
      </div>

  </div>


{% endblock %}

student_project/templates/admin.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.register') }}">Add Student</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('core.index') }}">View Students</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('teachers.add_teacher') }}" tabindex="-1">Add Teacher</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('teachers.view_teacher') }}" tabindex="-1">View Teacher</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('courses.add_course') }}" tabindex="-1">Add Course</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('courses.view_course') }}" tabindex="-1">View Courses</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>
{% endblock %}

student_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
    <link rel="stylesheet" href="static/styles.css" ></style>
    <link rel="stylesheet" href="static/register.css" ></style>

    <title>Student Project</title>

</head>
<body>

<!--Write in body section the codes-->
<!--Body section-->
<div class="html-container">
    <div class="html-section">
        <div class="html-project">
            <div class="navigation">
                <nav>
                    <ul class="nav-type">
                        <li><a href="{{ url_for('core.index') }}"  class="active">Home</a></li>
                        <li><a href="{{ url_for('core.info') }}"  class="active1">About</a></li>
                        {% if current_user.id == 1 %}
                        <li><a href="{{ url_for('users.admin_page') }}" class="active2">Admin page</a></li>
                        {% endif %}
                        {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('users.account') }} " class="active2">Account</a></li>
                        <li><a href="{{ url_for('users.logout') }} " class="active2">Logout</a></li>
                        {% else %}
                        <li><a href="{{ url_for('users.login') }}"  class="active2">Login</a></li>
                        <li><a href="{{ url_for('users.register') }}"  class="active3">Register</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>
{% for mess in get_flashed_messages() %}
<div class="alert alert-success alert-dismissible fad show" role="alert">
    <button type="button" class="fade close" data-dismiss="alert" aria-label="close">
        <span class="aria-hidden">&times;</span>
    </button>
    {{ mess }}

</div>
{% endfor %}

{% block content %}

{% endblock %}


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

student_project/templates/course.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <table class="table table-striped table-dark">
        <tr>
            <th>
                Course Name
            </th>
            <th>
                Description
            </th>
            <th>
                Student
            </th>
            <th>
                Teacher
            </th>
        </tr>
        {% for course in courses %}
        <tr>
            <td> {{ course.course_name }} </td>
            <td> {{ course.description }} </td>
            <td> {{ course.author1.full_name }} </td>
            <td> {{ course.author2.teacher_name }} </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

student_project/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
    <h1 align="center" style="color: black">List of all our students</h1>
<div class="container">
    <table class="table table-striped table-dark">
        <tr>
            <th>
                Full Name
            </th>
            <th>
                Email
            </th>
            <th>
                Phone number
            </th>
            <th>
                Photo
            </th>
        </tr>
        {% for student in students %}
        <tr>
            <td> {{ student.full_name }} </td>
            <td> {{ student.email }} </td>
            <td> {{ student.phone_number }} </td>
             <td><img align="center" class="rounded-circle" src="{{ url_for('static', filename='images/' + student.profile_pic) }}"></td>
        </tr>
        {% endfor %}
    </table>
</div>
</div>



{% endblock %}

student_project/templates/info.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron rounded mt-5">
    <h1 class="text-info">What is the website for ?</h1>
    <p clss="text-white bg-dark">Contrary to popular belief,
        Lorem Ipsum is not simply random text.
        It has roots in a piece of classical Latin literature from 45 BC,
        making it over 2000 years old. Richard McClintock, a Latin professor at
        Hampden-Sydney College in Virginia, looked up one of the more obscure Lat
        in words, consectetur, from a Lorem Ipsum passage, and going through the cit
        es of the word in classical literature, discovered the undoubtable source.
        Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum"
        (The Extremes of Good and Evil) by Cicero, written in 45 BC.
        This book is a treatise on the theory of ethics, very popular during the Renaissance.
        The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
        The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.
        Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form,
        accompanied by English versions from the 1914 translation by H.
        Rackham.</p>
</div>
{% endblock %}

student_project/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="login-form">
  <form method="POST">
    {{ form.hidden_tag() }}
    <h1>Login</h1>
    <div class="content">
      <div class="input-field">
        {{ form.email(placeholder="Email") }}


        {{ form.password(placeholder="Password") }}

        <a href="#" class="link">Forgot Your Password?</a>
      </div>
    </div>
    <div class="action">
      {{ form.submit(class="button") }}
      <a href="{{ url_for('users.register') }}" style="text-decoration: none;" class="button sign-in">Sign Up</a>
    </div>
  </form>
</div>
{% endblock content %}

student_project/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="parent">
	<div class="main">

		<div class="signup">
			<form method="POST">
				{{ form.hidden_tag() }}
				<label for="chk" aria-hidden="true">Sign up</label>
				{{ form.full_name(placeholder="Full Name") }}
				{{ form.email(placeholder="Email") }}
				{{ form.phone_number(placeholder="Phone Number") }}
				{{ form.password(placeholder="Password") }}
				{{ form.confirm_pass(placeholder="Confirm Password") }}
					{{ form.submit(class="button") }}
			</form>
		</div>

	</div>
</div>
{% endblock %}

student_project/templates/teacher.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <table class="table table-striped">
        <tr>
            <th>
                Teacher Name
            </th>
             <th>
                Email
            </th>
            <th>
                Description
            </th>
            <th>
                Profile Picture
            </th>
            <th>
                Student
            </th>
        </tr>
        {% for teacher in teachers %}
        <tr>
            <td> {{ teacher.teacher_name }} </td>
            <td> {{ teacher.email }} </td>
            <td> {{ teacher.description }} </td>
            <td><img align="center" class="rounded-circle" src="{{ url_for('static', filename='images/' + teacher.teach_profile) }}"></td>
            <td> {{ teacher.user_id }} </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

student_project/templates/view_student.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <table class="table table-striped table-dark">
        <tr>
            <th>
                Full Name
            </th>
            <th>
                Email
            </th>
            <th>
                Phone number
            </th>
            <th>
                Photo
            </th>
        </tr>
        {% for student in students %}
        <tr>
            <td> {{ student.full_name }} </td>
            <td> {{ student.email }} </td>
            <td> {{ student.phone_number }} </td>
             <td><img align="center" class="rounded-circle" src="{{ url_for('static', filename='images/' + student.profile_pic) }}"></td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}